import { useState } from 'react';
import { Link } from 'react-router-dom';
import axios from 'axios';
import { ShieldCheck, Upload, AlertCircle, ArrowLeft, RefreshCw, CheckCircle, HelpCircle, Heart } from 'lucide-react';
import VoicePrintSignature from '../components/VoicePrintSignature';

const API = import.meta.env.VITE_API_URL || (import.meta.env.DEV ? 'http://127.0.0.1:8000' : '');

export default function VerifyVoice() {
  const [file, setFile] = useState(null);
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState(null);
  const [error, setError] = useState(null);
  const [dragActive, setDragActive] = useState(false);

  // Client-side SHA-256 hashing using Web Crypto API
  const calculateHash = async (audioFile) => {
    const arrayBuffer = await audioFile.arrayBuffer();
    const hashBuffer = await window.crypto.subtle.digest('SHA-256', arrayBuffer);
    const hashArray = Array.from(new Uint8Array(hashBuffer));
    return hashArray.map(b => b.toString(16).padStart(2, '0')).join('');
  };

  const handleDrag = (e) => {
    e.preventDefault();
    e.stopPropagation();
    if (e.type === "dragenter" || e.type === "dragover") {
      setDragActive(true);
    } else if (e.type === "dragleave") {
      setDragActive(false);
    }
  };

  const handleDrop = async (e) => {
    e.preventDefault();
    e.stopPropagation();
    setDragActive(false);
    if (e.dataTransfer.files && e.dataTransfer.files[0]) {
      await processFile(e.dataTransfer.files[0]);
    }
  };

  const handleFileChange = async (e) => {
    if (e.target.files && e.target.files[0]) {
      await processFile(e.target.files[0]);
    }
  };

  const processFile = async (selectedFile) => {
    if (!selectedFile.type.startsWith('audio/')) {
      setError("Please upload a valid audio file (MP3, WAV, WEBM, etc.)");
      setFile(null);
      setResult(null);
      return;
    }

    setFile(selectedFile);
    setError(null);
    setResult(null);
    setLoading(true);

    try {
      // Calculate hash client-side (extremely fast, zero payload upload overhead)
      const fileHash = await calculateHash(selectedFile);
      
      // Request verification from the backend
      const res = await axios.post(`${API}/api/verify-voice/hash`, { hash: fileHash });
      setResult(res.data);
    } catch (err) {
      console.error("Verification failed:", err);
      setError("Failed to verify audio file. Please ensure the backend is running and try again.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-background text-primary flex flex-col font-sans px-4 py-8">
      {/* Back button */}
      <div className="max-w-xl w-full mx-auto mb-6">
        <Link 
          to="/" 
          className="inline-flex items-center gap-2 text-xs font-semibold uppercase tracking-wider border border-border hover:bg-surface/50 px-3.5 py-1.5 rounded-lg shadow-sm transition-all"
        >
          <ArrowLeft className="w-3.5 h-3.5" />
          <span>Back to Home</span>
        </Link>
      </div>

      <div className="max-w-xl w-full mx-auto bg-surface border-2 border-border p-8 rounded-2xl shadow-[6px_6px_0px_#2A160D] flex-1 flex flex-col justify-between">
        <div className="space-y-6">
          {/* Header */}
          <div className="text-center space-y-2 border-b border-border/80 pb-6">
            <div className="inline-flex p-3 bg-accent/10 border border-accent/30 rounded-2xl text-accent mb-2">
              <ShieldCheck className="w-8 h-8" />
            </div>
            <h1 className="text-3xl font-serif font-bold tracking-tight">Authenticity Checker</h1>
            <p className="text-xs text-secondary max-w-sm mx-auto leading-relaxed">
              Verify if an audio file is an authorized voice print generated by the Pratidhvani legacy preservation network.
            </p>
          </div>

          {/* Drag & Drop Zone */}
          <div 
            onDragEnter={handleDrag}
            onDragOver={handleDrag}
            onDragLeave={handleDrag}
            onDrop={handleDrop}
            className={`border-2 border-dashed rounded-xl p-8 text-center transition-all relative flex flex-col items-center justify-center min-h-[180px] ${
              dragActive 
                ? 'border-accent bg-accent/5' 
                : file 
                  ? 'border-success/60 bg-success/5' 
                  : 'border-border/60 hover:border-border bg-surface/30'
            }`}
          >
            <input 
              type="file" 
              id="audio-upload"
              accept="audio/*" 
              onChange={handleFileChange}
              className="absolute inset-0 w-full h-full opacity-0 cursor-pointer"
            />
            {loading ? (
              <div className="space-y-3">
                <RefreshCw className="w-8 h-8 text-accent animate-spin mx-auto" />
                <p className="text-xs font-semibold">Calculating voice signatures...</p>
              </div>
            ) : file ? (
              <div className="space-y-3">
                <CheckCircle className="w-8 h-8 text-success mx-auto" />
                <div>
                  <p className="text-xs font-bold truncate max-w-xs">{file.name}</p>
                  <p className="text-[10px] text-secondary">{(file.size / 1024).toFixed(1)} KB • Click to swap file</p>
                </div>
              </div>
            ) : (
              <div className="space-y-3 pointer-events-none">
                <Upload className="w-8 h-8 text-secondary/60 mx-auto" />
                <div>
                  <p className="text-xs font-bold">Drag and drop audio file here</p>
                  <p className="text-[10px] text-secondary">or click to browse from files</p>
                </div>
              </div>
            )}
          </div>

          {/* Error Message */}
          {error && (
            <div className="bg-danger/10 border border-danger/40 text-danger p-3.5 rounded-lg flex items-start gap-2 text-xs">
              <AlertCircle className="w-4 h-4 shrink-0 mt-0.5" />
              <span>{error}</span>
            </div>
          )}

          {/* Print isolation style */}
          <style dangerouslySetInnerHTML={{__html: `
            @media print {
              body * {
                visibility: hidden;
              }
              .print-certificate-container, .print-certificate-container * {
                visibility: visible;
              }
              .print-certificate-container {
                position: absolute;
                left: 0;
                top: 20px;
                width: 100%;
                border: 2px solid #2A160D !important;
                box-shadow: none !important;
                background: #FDF5D7 !important;
                color: #2A160D !important;
                padding: 24px !important;
                border-radius: 12px !important;
              }
              .no-print {
                display: none !important;
              }
            }
          `}} />

          {/* Result View */}
          {result && (
            <div className={`print-certificate-container border-2 rounded-xl p-6 space-y-5 transition-all ${
              result.authentic 
                ? 'border-success bg-surface shadow-[4px_4px_0px_#10B981]' 
                : 'border-danger bg-danger/5 shadow-[4px_4px_0px_#EF4444]'
            }`}>
              <div className="flex flex-col md:flex-row items-center gap-5">
                <div className="shrink-0">
                  <VoicePrintSignature hash={result.hash} isAuthentic={result.authentic} size={150} />
                </div>
                
                <div className="flex-1 w-full space-y-3">
                  <div className="flex items-center gap-2.5">
                    <span className={`p-1.5 rounded-lg text-background shrink-0 ${
                      result.authentic ? 'bg-success' : 'bg-danger'
                    }`}>
                      {result.authentic ? (
                        <ShieldCheck className="w-4 h-4" />
                      ) : (
                        <AlertCircle className="w-4 h-4" />
                      )}
                    </span>
                    <div>
                      <h3 className="font-serif font-bold text-base text-primary">
                        {result.authentic ? "Verified Authentic Voice Print" : "Verification Failed"}
                      </h3>
                      <p className="text-[10px] text-secondary font-mono truncate max-w-[240px]" title={result.hash}>
                        SHA-256: {result.hash}
                      </p>
                    </div>
                  </div>

                  {result.authentic ? (
                    <div className="border-t border-border/10 pt-3 space-y-2.5 text-xs text-secondary leading-relaxed">
                      <div className="flex justify-between border-b border-border/5 pb-1">
                        <span>Authorized Narrator:</span>
                        <span className="font-bold text-primary">{result.narrator_name}</span>
                      </div>
                      <div className="flex justify-between border-b border-border/5 pb-1">
                        <span>Registry Authority:</span>
                        <span className="font-semibold text-accent">Pratidhvani Trust Node</span>
                      </div>
                      <div className="flex justify-between">
                        <span>Signature Date:</span>
                        <span className="font-mono">{new Date(result.generated_at).toLocaleString()}</span>
                      </div>
                    </div>
                  ) : (
                    <p className="text-xs text-secondary leading-relaxed">
                      This audio print was not generated by the Pratidhvani legacy network or has been tampered with. It is flagged as an **unauthorized synthesis** and should not be trusted.
                    </p>
                  )}
                </div>
              </div>

              {result.authentic && (
                <div className="border-t border-border/10 pt-3 flex flex-col gap-1.5 text-left">
                  <span className="text-[9px] uppercase tracking-wider text-accent font-bold">Speech Content Transcript:</span>
                  <p className="font-serif italic text-primary font-medium bg-background/30 border border-border/30 rounded-lg p-3 text-xs leading-relaxed shadow-sm">
                    "{result.transcript}"
                  </p>
                  
                  <div className="no-print flex justify-end pt-3 border-t border-border/5">
                    <button
                      onClick={() => window.print()}
                      className="px-4 py-2 border-2 border-border text-[10px] uppercase tracking-widest font-bold bg-primary text-background hover:bg-accent transition-all active:scale-[0.97] shadow-[2px_2px_0px_#2A160D]"
                    >
                      Print Trust Certificate
                    </button>
                  </div>
                </div>
              )}
            </div>
          )}
        </div>

        {/* Footer info */}
        <div className="border-t border-border/80 pt-6 mt-6 text-center space-y-4">
          <div className="flex justify-center items-center gap-1.5 text-[10px] text-secondary font-semibold">
            <Heart className="w-3 h-3 text-accent fill-accent/20" />
            <span>Secured by Pratidhvani Legacy Cryptographic Registry</span>
          </div>
        </div>
      </div>
    </div>
  );
}
